spring.application.name=Journal

server.port=8080

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.uri=mongodb://localhost:27017/journaldb


