spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080



#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/journal
#spring.datasource.username=root
#spring.datasource.password=2020



spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.uri=mongodb://localhost:27017/journal












